### PR TITLE
Fix #1460

### LINKED ISSUE #1460: rawsockets doesn't work with cpp backend
```nimrod
import rawsockets
```
Error:
```
/home/deen/git/nimrod-unsorted/nimcache/stdlib_rawsockets.cpp: In function ‘addrinfo* getaddrinfo_142208(NimStringDesc*, NU16, NU8, NU8, NU8)’:
/home/deen/git/nimrod-unsorted/nimcache/stdlib_rawsockets.cpp:579:32: error: invalid conversion from ‘const char*’ to ‘NCSTRING {aka char*}’ [-fpermissive]
   LOC6 = gai_strerror(gairesult);
                                ^
/home/deen/git/nimrod-unsorted/nimcache/stdlib_rawsockets.cpp: In function ‘void gethostbyaddr_143246(NimStringDesc*, thostent141421*)’:
/home/deen/git/nimrod-unsorted/nimcache/stdlib_rawsockets.cpp:787:27: error: invalid conversion from ‘const char*’ to ‘NCSTRING {aka char*}’ [-fpermissive]
   LOC5 = hstrerror(h_errno);
```

### PR DESCRIPTION
**Pull request by def-**
Since I couldn't get array return types working, only the working part from this: https://github.com/Araq/Nim/pull/2424

### CODE REVIEW

File: compiler/main.nim [hunk 1]
```diff
@@ -54,6 +54,7 @@ proc commandDoc2 =
   finishDoc2Pass(gProjectName)
 
 proc commandCompileToC =
+  extccomp.initVars()
```
Comment (Araq) [inline compiler/main.nim]: What does this fix?

Comment (def-) [inline compiler/main.nim]: In https://github.com/Araq/Nim/commit/53f4c7758b0c9d3df562795eeca0a553eb22e219 you removed the `setCC("gcc")`. Now the `.options.always` are read only once with the first call to `initVars`, but then `cpp` is not defined yet, so `gcc.options.always` are used instead of `gcc.cpp.options.always`. Since we don't want to use `setCC("gcc")` so as not to introduce #1601 again, I call `initVars` again, after `cpp` should be set. Maybe there's a better way to do this.

**Comment by def-** [comment]
Would be nice to have this in before the 0.10.4 release, as many modules are broken with C++ backend now, but worked before.
