### PR TITLE
Apply strongSpaces to keyword operators too. Fix #1894.

### LINKED ISSUE #1894: Wrong precedence for shl (and related) operators with #!strongSpaces
The `shl` should have higher precedence than addition, and it does, but when one ads the #!strongSpaces pre-processor it's priority falls:
``` Nimrod
#!strongSpaces
 
echo 1 + 16 shl 1 # prints 34
echo 1 + 16 shl 1 == 1 + (16 shl 1) # compilation error
````
The second echo gives the error:

>/tmp/aporia/a0.nim(3, 12) Error: type mismatch: got (int literal(17), bool)
but expected one of:
system.shl(x: int32, y: int32): int32
system.shl(x: int16, y: int16): int16
system.shl(x: int8, y: int8): int8
system.shl(x: int, y: int): int
system.shl(x: int64, y: int64): int64
> Process terminated with exit code 256
""" 

This probably applies to other keyword bitwise operators too.

### PR DESCRIPTION
**Pull request by ReneSac**
When #!strongSpaces is on, every operator affected by it gains priority higher than any operator not affected by it. This includes comparison operators, addition, etc. Hence the bug #1894. The way to fix it is to apply it to all operators.

It seems that counting spaces for keywords operators don't break anything in the parser. Of course, they can't have 0 spaces between their operands, but at least their precedence will work accordingly to their 1+ spaces.

I had to change one of the tests to compile, as the strongSpaces rule was extended to `and` too. I compiled some other unrelated things (including the compiler itself) and nothing seems broken.

### CODE REVIEW

File: tests/parser/tstrongspaces.nim [hunk 1]
```diff
@@ -27,7 +44,7 @@ when true:
   let b = 66
   let c = 90
   let bar = 8000
-  if foo+4 * 4 == 8 and b&c | 9  ++
+  if foo+4 * 4 == 8  and  b&c | 9  ++
```
Comment (Araq) [inline tests/parser/tstrongspaces.nim]: This is unfortunate though. Does 'and' with single spaces still work for most other things like ``x+y == 8 and foo*8 <= 90``?

Comment (ReneSac) [inline tests/parser/tstrongspaces.nim]: For reference: http://nim-lang.org/manual.html#precedence

I considered not applying the strongSpaces rule to keyword operators with priority lower than the comparison operators (lower than 5). That would be `and` `or` `xor`. The problem is that then `@ : ?``operators and arrow like operators would have always a priority higher than them, changing the priority rules. Then I settled with this consistent rule, applying it to everything.

Another possibility is to apply the strongSpaces rule only to arithmetic operators. For all precedence levels 5/6/7 (not sure where to start) and above, and only them. This would be a bigger change, but maybe more what you imagine being ideal.

By the way, in the docs the arrow like operator has precedence 0, but in the code it has precedence 1, and gets higher precedence than assignment operators when strongSpaces is on. This is a bug?

**Comment by ReneSac** [comment]
For reference: http://nim-lang.org/manual.html#precedence

I considered not applying the strongSpaces rule to keyword operators with priority lower than the comparison operators (lower than 5). That would be `and` `or` `xor`. The problem is that then `@ : ?``operators and arrow like operators would have always a priority higher than them, changing the priority rules. Then I settled with this consistent rule, applying it to everything.

Another possibility is to apply the strongSpaces rule only to arithmetic operators. For all precedence levels 5/6/7 (not sure where to start) and above, and only them. This would be a bigger change, but maybe more what you imagine being ideal.

By the way, in the docs the arrow like operator has precedence 0, but in the code it has precedence 1, and gets higher precedence than assignment operators when strongSpaces is on. This is a bug?

**Comment by Araq** [comment]
> This is a bug?

No, the spec and the parser do not have to agree on the particular numbers.
